const { cmd } = require("../command");
const axios = require("axios");
const fs = require("fs");
const path = require("path");

cmd({
    pattern: "img",
    alias: ["quzimg", "genimg", "teaimg", "aiimage", "txt2img"],
    react: "🎨",
    desc: "Generate AI images from text (100% Free)",
    category: "ai",
    filename: __filename,
},
async (bot, mek, m, { from, q, reply }) => {
    try {
        if (!q) {
            return reply("🎨 *Please describe your image*\n\nExample: .aimg a beautiful sunset over mountains, digital art");
        }

        // Generate karana message eka
        await bot.sendMessage(from, {
            text: `🎨 *Generating your AI image...*\n\n📝 *Prompt:* ${q}\n⏳ Please wait 20-30 seconds`
        }, { quoted: mek });

        // Free AI Image API - Pollinations AI (100% free, no key needed)
        const imageUrl = `https://image.pollinations.ai/prompt/${encodeURIComponent(q)}?width=1024&height=1024&nologo=true`;
        
        // Download image
        const imagePath = path.join(__dirname, `${Date.now()}_ai.jpg`);
        
        const response = await axios({
            url: imageUrl,
            method: 'GET',
            responseType: 'stream',
            timeout: 60000
        });
        
        const writer = fs.createWriteStream(imagePath);
        response.data.pipe(writer);
        
        await new Promise((resolve, reject) => {
            writer.on('finish', resolve);
            writer.on('error', reject);
        });

        // Image eka INBOX ekata send karanawa
        await bot.sendMessage(from, {
            image: fs.readFileSync(imagePath),
            caption: `🎨 *AI Image Generated*\n\n📝 *Prompt:* ${q}\n\n✨ Generated by Pollinations AI\n✅ 100% Free\n\n> MALIYA-MD ❤️`
        }, { quoted: mek });

        // Delete temp file
        fs.unlinkSync(imagePath);
        
    } catch (e) {
        console.log("AI Image Error:", e);
        reply("❌ Error generating image. Trying alternative method...");
        
        try {
            // Alternative API - Stable Diffusion
            const altUrl = `https://api.nexra.aryahcr.cc/image/stable-diffusion?prompt=${encodeURIComponent(q)}&model=sd-1.5`;
            
            const altResponse = await axios.get(altUrl);
            
            if (altResponse.data && altResponse.data.images && altResponse.data.images[0]) {
                const imgBuffer = Buffer.from(altResponse.data.images[0], 'base64');
                
                await bot.sendMessage(from, {
                    image: imgBuffer,
                    caption: `🎨 *AI Image Generated*\n\n📝 *Prompt:* ${q}\n\n✨ Generated via Alternative API\n✅ 100% Free\n\n> MALIYA-MD ❤️`
                }, { quoted: mek });
            } else {
                throw new Error("No image generated");
            }
            
        } catch (altError) {
            console.log("Alternative Error:", altError);
            reply("❌ Failed to generate image. Please try again later.");
        }
    }
});
